### ISSUE TITLE
After Completing checkout, items are not appearing in the list.

### ISSUE THREAD

**Issue by trevren11** [BYU-ODH/hlrdesk#333] opened 2015-10-08 16:08 UTC

**Comment by stevethomas19** [comment] 2016-04-11 21:05
I'm currently investigating the issue. http://screencast.com/t/bn1FdjqYrA
This video shows that when a user goes to check something out:

1. The success message shows
2. The item is not found in the check-in list
3. The item is not found in the checked_out db list
4. When you go to check it out again you can select it from the list
5. When you confirm checkout (again) it gives you an error message that it has already been checked out.
6. Its not checked out...

I'm mostly documenting this for my own purposes, but if  any of you (@trevren11. @webnard , @alexcdahl) have any idea as to why this is happening I'd like to hear it.

**Comment by stevethomas19** [comment] 2016-04-11 21:09
Another video: http://screencast.com/t/hcTcyAI2KZ

1. The success message shows
2. The item is not found in the check-in list
3. The item is not found in the checked_out db list
4. When you checkout a different item the first one you selected gets checked out...

**Comment by stevethomas19** [comment] 2016-04-11 21:19
Another video: http://screencast.com/t/iwJXD63G

1. It worked...

As you can tell from these videos I really am doing nothing different. I am getting WAY different results.

**Comment by stevethomas19** [comment] 2016-04-13 19:40
@webnard I don't know how full your plate is at the moment, but this might be an issue you have to look into. I don't understand enough about generators, promises and yield to determine why sometimes this is working and sometimes it isn't. You can look at the videos above to see examples of things that are happening.

**Comment by webnard** [comment] 2016-04-15 20:47
I'm seeing this, too, now. Looks like it's an issue with a transaction that isn't sent immediately.

**Comment by webnard** [comment] 2016-04-15 20:47
@stevethomas19

**Comment by webnard** [comment] 2016-04-15 20:51
@stevethomas19 Actually, on further inspection, it's an issue with transactions caused by a race condition as suggested by @dcravenus. The BEGIN TRANSACTION and COMMIT calls are not yielded, so they're not guaranteed to be synchronous. The BEGIN TRANSACTION and COMMIT phases are getting jumbled up. What you're probably seeing is the transaction beginning but never being committed (maybe COMMIT is called prior to BEGIN TRANSACTION), and so Postgres waits for another COMMIT call before the transaction is finished (for example, when you try and check something out again, commit is then called a second time).

I'll fix the issue and send up a pull request.

**Closed** 2016-04-26 18:57 UTC
Labels: in progress
